CREATE DATABASE DB_ECOMMERCE;

USE DB_ECOMMERCE;

CREATE TABLE TB_PRODUTOS(
ID BIGINT AUTO_INCREMENT,
PRODUTO VARCHAR(1000),
MODELO VARCHAR(1000),
COR VARCHAR(1000),
PRECO FLOAT,
PRIMARY KEY (ID)
);

INSERT INTO TB_PRODUTOS (PRODUTO, MODELO, COR, PRECO) VALUES ("CELULAR", "APPLE", "VERMELHO", 3500.00);
INSERT INTO TB_PRODUTOS (PRODUTO, MODELO, COR, PRECO) VALUES ("NOTEBOOK", "SAMSUNG", "PRETO", 4200.00);
INSERT INTO TB_PRODUTOS (PRODUTO, MODELO, COR, PRECO) VALUES ("JOGO DE PANELA", "BRINOX", "GRAFITE", 199.00);
INSERT INTO TB_PRODUTOS (PRODUTO, MODELO, COR, PRECO) VALUES ("POLTRONA", "FLORENCA", "MARROM", 499.00);
INSERT INTO TB_PRODUTOS (PRODUTO, MODELO, COR, PRECO) VALUES ("CORTINA", "BLACKOUT", "AVELÃ", 109.90);
INSERT INTO TB_PRODUTOS (PRODUTO, MODELO, COR, PRECO) VALUES ("SOFÁ RETRÁTIL", "VENEZA", "BEGE", 2490.00);
INSERT INTO TB_PRODUTOS (PRODUTO, MODELO, COR, PRECO) VALUES ("APARELHO DE JANTAR", "OXFORD", "AZUL/BRANCO", 799.00);
INSERT INTO TB_PRODUTOS (PRODUTO, MODELO, COR, PRECO) VALUES ("GARRAFA TÉRMICA", "TRAMONTINA", "AZUL", 99.00);
INSERT INTO TB_PRODUTOS (PRODUTO, MODELO, COR, PRECO) VALUES ("GELADEIRA", "CONSUL", "INOX", 2900.00);

SELECT * FROM TB_PRODUTOS;

SET SQL_SAFE_UPDATES = 0;

SELECT * FROM TB_PRODUTOS WHERE PRECO > 500.00;

SELECT * FROM TB_PRODUTOS WHERE PRECO < 500.00;

UPDATE TB_PRODUTOS SET COR = "ROSA" WHERE ID = 8;

SELECT * FROM TB_PRODUTOS WHERE ID = 8;


