CREATE DATABASE DB_ESCOLA;

USE DB_ESCOLA;

CREATE TABLE TB_ESTUDANTES(
RA BIGINT AUTO_INCREMENT,
ALUNO VARCHAR(1000), 
IDADE INT, 
TURNO CHAR(255),
MEDIANOTA FLOAT,
PRIMARY KEY (RA)
);

INSERT INTO TB_ESTUDANTES (ALUNO, IDADE, TURNO, MEDIANOTA) VALUES ("ANA PAULA NUNES", 16, "NOTURNO", 8.7);
INSERT INTO TB_ESTUDANTES (ALUNO, IDADE, TURNO, MEDIANOTA) VALUES ("NATALIA PEREIRA", 18, "NOTURNO", 9);
INSERT INTO TB_ESTUDANTES (ALUNO, IDADE, TURNO, MEDIANOTA) VALUES ("HEITOR NABAS", 6, "TARDE", 9.2);
INSERT INTO TB_ESTUDANTES (ALUNO, IDADE, TURNO, MEDIANOTA) VALUES ("NOAH NUNES", 10, "MANHÃ", 6.3);
INSERT INTO TB_ESTUDANTES (ALUNO, IDADE, TURNO, MEDIANOTA) VALUES ("RODRIGO FERREIRA", 20, "NOTURNO", 5.5);
INSERT INTO TB_ESTUDANTES (ALUNO, IDADE, TURNO, MEDIANOTA) VALUES ("LETICIA RODRIGUES", 15, "TARDE", 4.8);
INSERT INTO TB_ESTUDANTES (ALUNO, IDADE, TURNO, MEDIANOTA) VALUES ("FELIPE ARAÚJO", 16, "NOTURNO", 10);
INSERT INTO TB_ESTUDANTES (ALUNO, IDADE, TURNO, MEDIANOTA) VALUES ("FERNANDA FERNANDES", 5, "MANHÃ", 8.9);

SELECT * FROM TB_ESTUDANTES;

SET SQL_SAFE_UPDATES = 0;

SELECT * FROM TB_ESTUDANTES WHERE MEDIANOTA > 7;

SELECT * FROM TB_ESTUDANTES WHERE MEDIANOTA < 7;

UPDATE TB_ESTUDANTES SET IDADE = 7 WHERE RA = 3;

SELECT * FROM TB_ESTUDANTES WHERE RA = 3;
