CREATE DATABASE DB_FARMACIA_BEM_ESTAR;
USE DB_FARMACIA_BEM_ESTAR; 

CREATE TABLE TB_CATEGORIAS(
ID BIGINT AUTO_INCREMENT, 
REMEDIOS VARCHAR(255), 
PERFUMARIA VARCHAR (255), 
PRIMARY KEY (ID));

CREATE TABLE TB_PRODUTOS(
ID BIGINT AUTO_INCREMENT, 
PRODUTO VARCHAR(255) NOT NULL, 
QUANTIDADE INT NOT NULL,
PRECO DECIMAL (6,2) NOT NULL, 
CATEGORIAS_ID BIGINT,
PRIMARY KEY (ID), 
FOREIGN KEY (CATEGORIAS_ID) REFERENCES TB_CATEGORIAS (ID));

INSERT INTO TB_CATEGORIAS (REMEDIOS, PERFUMARIA) VALUES ("COMPRIMIDOS", "BEBÊ");
INSERT INTO TB_CATEGORIAS (REMEDIOS, PERFUMARIA) VALUES ("LÍQUIDO", "FEMININOS");
INSERT INTO TB_CATEGORIAS (REMEDIOS, PERFUMARIA) VALUES ("DORES MUSCULARES", "MASCULINOS");
INSERT INTO TB_CATEGORIAS (REMEDIOS, PERFUMARIA) VALUES ("XAROPE", "CORPORAL");
INSERT INTO TB_CATEGORIAS (REMEDIOS, PERFUMARIA) VALUES ("GRIPE", "CABELOS");

SELECT * FROM TB_CATEGORIAS;

INSERT INTO TB_PRODUTOS (PRODUTO, QUANTIDADE, PRECO, CATEGORIAS_ID) VALUES ("DIPIRONA", 30, 16.00, 1);
INSERT INTO TB_PRODUTOS (PRODUTO, QUANTIDADE, PRECO, CATEGORIAS_ID) VALUES ("VICK", 18, 26.00, 4);
INSERT INTO TB_PRODUTOS (PRODUTO, QUANTIDADE, PRECO, CATEGORIAS_ID) VALUES ("FRALDAS", 10, 68.00, 1);
INSERT INTO TB_PRODUTOS (PRODUTO, QUANTIDADE, PRECO, CATEGORIAS_ID) VALUES ("AMOXICILINA", 8, 32.00, 1);
INSERT INTO TB_PRODUTOS (PRODUTO, QUANTIDADE, PRECO, CATEGORIAS_ID) VALUES ("DORFLEX", 22, 12.00, 3);
INSERT INTO TB_PRODUTOS (PRODUTO, QUANTIDADE, PRECO, CATEGORIAS_ID) VALUES ("CIMEGRIPE", 5, 13.00, 5);
INSERT INTO TB_PRODUTOS (PRODUTO, QUANTIDADE, PRECO, CATEGORIAS_ID) VALUES ("DOVE", 6, 28.00, 5);
INSERT INTO TB_PRODUTOS (PRODUTO, QUANTIDADE, PRECO, CATEGORIAS_ID) VALUES ("EXPEC", 8, 16.00, 4);

SELECT * FROM TB_PRODUTOS;

SELECT * FROM TB_PRODUTOS WHERE PRECO > 50.00;
SELECT * FROM TB_PRODUTOS WHERE PRECO BETWEEN 5.00 AND 60.00;
SELECT * FROM TB_PRODUTOS WHERE PRODUTO LIKE "%C%";
SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIAS ON TB_PRODUTOS.CATEGORIAS_ID = TB_CATEGORIAS.ID;
SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIAS ON TB_PRODUTOS.CATEGORIAS_ID = TB_CATEGORIAS.ID WHERE REMEDIOS = "COMPRIMIDOS";
