CREATE DATABASE DB_GENERATION_GAME_ONLINE;
USE DB_GENERATION_GAME_ONLINE;

CREATE TABLE TB_CLASSES(
ID BIGINT AUTO_INCREMENT,
PRIMARIO VARCHAR (255),
FRAQUEZAS VARCHAR (255),
PRIMARY KEY (ID));

CREATE TABLE TB_PERSONAGENS(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(255),
ATAQUE VARCHAR(255),
ARMADURA VARCHAR(255), 
CLASSES_ID BIGINT,
PRIMARY KEY (ID),
FOREIGN KEY (CLASSES_ID) REFERENCES TB_CLASSES(ID));

INSERT INTO TB_CLASSES (PRIMARIO, FRAQUEZAS) VALUES ("FORÇA", "DELÍRIO");
INSERT INTO TB_CLASSES (PRIMARIO, FRAQUEZAS) VALUES ("DEFESA", "POUCO GANHO XP");
INSERT INTO TB_CLASSES (PRIMARIO, FRAQUEZAS) VALUES ("AGILIDADE", "ESQUECIMENTO");
INSERT INTO TB_CLASSES (PRIMARIO, FRAQUEZAS) VALUES ("VELOCIDADE", "POUCA FORÇA");
INSERT INTO TB_CLASSES (PRIMARIO, FRAQUEZAS) VALUES ("INTELIGÊNCIA", "DEVAGAR");

SELECT * FROM TB_CLASSES;

INSERT INTO TB_PERSONAGENS (NOME, ATAQUE, ARMADURA, CLASSES_ID) VALUES ("CHUN-LI", 3400, "DOURADA", 2);
INSERT INTO TB_PERSONAGENS (NOME, ATAQUE, ARMADURA, CLASSES_ID) VALUES ("LINK", 5000, "DOURADA", 1);
INSERT INTO TB_PERSONAGENS (NOME, ATAQUE, ARMADURA, CLASSES_ID) VALUES ("LARA", 2200, "DIAMANTE", 3);
INSERT INTO TB_PERSONAGENS (NOME, ATAQUE, ARMADURA, CLASSES_ID) VALUES ("KONG", 1600, "BRONZE", 5); 
INSERT INTO TB_PERSONAGENS (NOME, ATAQUE, ARMADURA, CLASSES_ID) VALUES ("TERRY", 6100, "PRATA", 4);
INSERT INTO TB_PERSONAGENS (NOME, ATAQUE, ARMADURA, CLASSES_ID) VALUES ("BOB", 3700, "DIAMANTE", 2);
INSERT INTO TB_PERSONAGENS (NOME, ATAQUE, ARMADURA, CLASSES_ID) VALUES ("LIRA", 1100, "BRONZE", 3);
INSERT INTO TB_PERSONAGENS (NOME, ATAQUE, ARMADURA, CLASSES_ID) VALUES ("TIARA", 7200, "DIAMANTE", 4);

SELECT *FROM TB_PERSONAGENS;

DELETE FROM TB_PERSONAGENS WHERE ID=1 OR ID=2 OR ID=3 OR ID=4 OR ID=5;

SELECT * FROM TB_PERSONAGENS WHERE ATAQUE > 2000;
SELECT * FROM TB_PERSONAGENS WHERE ATAQUE BETWEEN 1000 AND 2000;
SELECT * FROM TB_PERSONAGENS WHERE NOME LIKE "C%";
SELECT * FROM TB_PERSONAGENS INNER JOIN TB_CLASSES ON TB_PERSONAGENS.CLASSES_ID = TB_CLASSES.ID;

SELECT * FROM TB_PERSONAGENS INNER JOIN TB_CLASSES ON TB_PERSONAGENS.CLASSES_ID = TB_CLASSES.ID WHERE PRIMARIO = "DEFESA";
