CREATE DATABASE DB_PIZZARIA_LEGAL;
USE DB_PIZZARIA_LEGAL;

CREATE TABLE TB_CATEGORIAS(
ID BIGINT AUTO_INCREMENT,
SALGADAS VARCHAR(255) NOT NULL,
DOCES VARCHAR(255) NOT NULL,
PRIMARY KEY (ID));

CREATE TABLE TB_PIZZAS(
ID BIGINT AUTO_INCREMENT,
SABOR VARCHAR(255) NOT NULL,
BORDA VARCHAR (255) NOT NULL, 
PRECO DECIMAL (6,2) NOT NULL,
CATEGORIAS_ID BIGINT, 
PRIMARY KEY (ID), 
FOREIGN KEY (CATEGORIAS_ID) REFERENCES TB_CATEGORIAS(ID));

INSERT INTO TB_CATEGORIAS (SALGADAS, DOCES) VALUES ("4 PEDAÇOS", "4 PEDAÇOS");
INSERT INTO TB_CATEGORIAS (SALGADAS, DOCES) VALUES ("8 PEDAÇOS", "8 PEDAÇOS");
INSERT INTO TB_CATEGORIAS (SALGADAS, DOCES) VALUES ("VEGETARIANA", "SEM AÇUCAR");
INSERT INTO TB_CATEGORIAS (SALGADAS, DOCES) VALUES ("2 SABORES", "2 SABORES");
INSERT INTO TB_CATEGORIAS (SALGADAS, DOCES) VALUES ("1 SABOR", "1 SABOR");

SELECT * FROM TB_CATEGORIAS;

INSERT INTO TB_PIZZAS (SABOR, BORDA, PRECO, CATEGORIAS_ID) VALUES ("MUSSARELA", "CHEEDAR", 38.00, 2);
INSERT INTO TB_PIZZAS (SABOR, BORDA, PRECO, CATEGORIAS_ID) VALUES ("BRIGADEIRO", "DOCE DE LEITE", 42.00, 4);
INSERT INTO TB_PIZZAS (SABOR, BORDA, PRECO, CATEGORIAS_ID) VALUES ("PORTUGUESA", "CATUPIRY", 46.00, 1);
INSERT INTO TB_PIZZAS (SABOR, BORDA, PRECO, CATEGORIAS_ID) VALUES ("CALABRESA", "REQUEIJÃO", 39.00, 5);
INSERT INTO TB_PIZZAS (SABOR, BORDA, PRECO, CATEGORIAS_ID) VALUES ("BRÓCOLIS", "CATUPIRY", 28.00, 3);
INSERT INTO TB_PIZZAS (SABOR, BORDA, PRECO, CATEGORIAS_ID) VALUES ("ROMEU E JULIETA", "SEM BORDA", 55.00, 5);
INSERT INTO TB_PIZZAS (SABOR, BORDA, PRECO, CATEGORIAS_ID) VALUES ("DOCE DE LEITE", "BRIGADEIRO", 48.00, 2);
INSERT INTO TB_PIZZAS (SABOR, BORDA, PRECO, CATEGORIAS_ID) VALUES ("PRESTÍGIO", "SEM BORDA", 59.00, 4);

SELECT * FROM TB_PIZZAS;

DELETE FROM TB_PIZZAS WHERE ID=3;

SELECT * FROM TB_PIZZAS WHERE PRECO > 45.00;
SELECT * FROM TB_PIZZAS WHERE PRECO BETWEEN 50.00 AND 100.00;
SELECT * FROM TB_PIZZAS WHERE SABOR LIKE "%M%";
SELECT * FROM TB_PIZZAS INNER JOIN TB_CATEGORIAS ON TB_PIZZAS.CATEGORIAS_ID = TB_CATEGORIAS.ID;
SELECT * FROM TB_PIZZAS INNER JOIN TB_CATEGORIAS ON TB_PIZZAS.CATEGORIAS_ID = TB_CATEGORIAS.ID WHERE SALGADAS = "2 SABORES";